### ISSUE TITLE
"apollo-upload-server" has been deprecated

### ISSUE THREAD

**Issue by dimabory** [graphql-extended/gqlx-apollo-express-server#8]
> [apollo-upload-server](https://www.npmjs.com/package/apollo-upload-server) has been deprecated

![image](https://user-images.githubusercontent.com/11414342/87040837-f9315a00-c1f9-11ea-8585-447441d7fd9a.png)

Please read https://github.com/jaydenseric/graphql-upload/issues/68

It's available now as [graphql-upload](https://www.npmjs.com/package/graphql-upload).

**Comment by FlorianRappl** [comment]
Contributions appreciated.

Before tackling this it must be made compatible with `apollo-server-express@2`.

**Comment by dimabory** [comment]
Sure, it seems like a minimum node version should be also changed to `^10.13.0 || ^12.0.0 || >= 13.7.0`.

**Comment by FlorianRappl** [comment]
I think that spec is the least thing to worry ;). I would start by migrating to `apollo-server-express@2` and if that migration works update the dependencies + the remaining meta data.

**Comment by FlorianRappl** [comment]
Landed in `0.5.0`. Thanks a lot for the superb contribution @dimabory !
